from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'dashboard'

urlpatterns = [
    path('', views.home, name='home'),
    path('neo4j/', views.neo4j_dashboard, name='neo4j_dashboard'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='dashboard:login'), name='logout'),
    path('admin/user-management/', views.admin_user_management, name='admin_user_management'),
    path('get-existing-nodes/', views.get_existing_nodes_view, name='get_existing_nodes'),
    path('add-nodes/', views.add_nodes, name='add_nodes'),
    path('define-relations/', views.define_relations, name='define_relations'),
    path('confirm-relationships/', views.confirm_relationships, name='confirm_relationships'),  # مسیر جدید
    path('manual-queries/', views.manual_queries, name='manual_queries'),
    path('graph-view/', views.graph_view, name='graph_view'),
    path('admin-queries/', views.admin_queries, name='admin_queries'),
    path('delete-predefined-query/<str:query_id>/', views.delete_predefined_query, name='delete_predefined_query'),
    path('predefined-query/<str:query_id>/result/', views.predefined_query_result, name='predefined_query_result'),
    path('check-node-duplicate/', views.check_node_duplicate, name='check_node_duplicate'),
    path('explore-layers/', views.explore_layers, name='explore_layers'),
    path('predefined-queries/', views.predefined_queries, name='predefined_queries'),
    path('export-manual-query/', views.export_manual_query, name='export_manual_query'),
    path('test-impact-analysis/', views.test_impact_analysis, name='test_impact_analysis'),
    path('test-analysis/', views.test_analysis_dashboard, name='test_analysis'),
    path('get-test-coverage/', views.get_test_coverage, name='get_test_coverage'),
    path('get-test-results/', views.get_test_results, name='get_test_results'),
    path('get-impact-analysis/', views.get_impact_analysis, name='get_impact_analysis'),
    path('manage-nodes/', views.manage_nodes, name='manage_nodes'),  # New URL pattern
    path('api-tools/', views.api_tools, name='api_tools'),
    path('clear-api-session/', views.clear_api_session, name='clear_api_session'),
    path('authenticate-session/', views.authenticate_user_session, name='authenticate_user_session'),
    path('create-wallet/', views.create_wallet, name='create_wallet'),
    path('add-transaction/', views.add_transaction, name='add_transaction'),
    path('load-wallets-ajax/', views.load_wallets_ajax, name='load_wallets_ajax'),
    path('transaction-confirmation/', views.transaction_confirmation, name='transaction_confirmation'),
    path('transaction-management/', views.transaction_management, name='transaction_management'),
    path('feature-flags/', views.feature_flags, name='feature_flags'),
    path('search-user-for-feature-flags/', views.search_user_for_feature_flags, name='search_user_for_feature_flags'),
    path('get-feature-flags-ajax/', views.get_feature_flags_ajax, name='get_feature_flags_ajax'),
    path('get-user-feature-flags-ajax/', views.get_user_feature_flags_ajax, name='get_user_feature_flags_ajax'),
    path('create-feature-flag-ajax/', views.create_feature_flag_ajax, name='create_feature_flag_ajax'),
    path('search-user-by-mobile/', views.search_user_by_mobile, name='search_user_by_mobile'),
    path('get-transactions-ajax/', views.get_transactions_ajax, name='get_transactions_ajax'),
    path('transaction-action-ajax/', views.transaction_action_ajax, name='transaction_action_ajax'),
    path('validate-token-ajax/', views.validate_token_ajax, name='validate_token_ajax'),
    path('test-confirm-ajax/', views.test_confirm_ajax, name='test_confirm_ajax'),
    path('test-user-id-extraction/', views.test_user_id_extraction, name='test_user_id_extraction'),
    path('get-user-from-django-session/', views.get_user_from_django_session, name='get_user_from_django_session'),
    path('test-user-id-fetch/', views.test_user_id_fetch, name='test_user_id_fetch'),
    path('debug-session-extraction/', views.debug_session_extraction, name='debug_session_extraction'),
    path('debug-user-id-validation/', views.debug_user_id_validation, name='debug_user_id_validation'),
    path('debug-cookie-parsing/', views.debug_cookie_parsing, name='debug_cookie_parsing'),
    path('debug-csrf-extraction/', views.debug_csrf_extraction, name='debug_csrf_extraction'),
    path('debug-csrf-from-url/', views.debug_csrf_from_url, name='debug_csrf_from_url'),
    path('centralized-user-search/', views.centralized_user_search, name='centralized_user_search'),
    path('add-all-features-ajax/', views.add_all_features_ajax, name='add_all_features_ajax'),
    path('store-user-db-id/', views.store_user_db_id, name='store_user_db_id'),
    path('last-otp/', views.last_otp, name='last_otp'),
]
