# Generated by Django 4.2.18 on 2025-05-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('query_text', models.TextField(verbose_name='Query Text')),
                ('created_by', models.CharField(default='Admin', max_length=100, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Admin Query',
                'verbose_name_plural': 'Admin Queries',
            },
        ),
        migrations.CreateModel(
            name='PredefinedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('query_text', models.TextField(verbose_name='Query Text')),
                ('category', models.CharField(choices=[('General', 'General'), ('Analysis', 'Analysis'), ('Maintenance', 'Maintenance')], default='General', max_length=50)),
                ('created_by', models.CharField(default='Admin', max_length=100, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Predefined Query',
                'verbose_name_plural': 'Predefined Queries',
            },
        ),
        migrations.CreateModel(
            name='TestCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('coverage_percentage', models.FloatField()),
                ('lines_covered', models.IntegerField()),
                ('total_lines', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('SKIP', 'Skip')], max_length=20)),
                ('duration', models.FloatField()),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('test_file', models.CharField(max_length=255)),
                ('line_number', models.IntegerField()),
            ],
            options={
                'ordering': ['-last_run'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether the user has been approved by an admin.'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='dashboard_user',
        ),
        migrations.CreateModel(
            name='ComponentDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('dependency_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source', 'target', 'dependency_type')},
            },
        ),
    ]
