# Generated by Django 4.2.16 on 2025-02-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_savedquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query', models.TextField()),
            ],
        ),
    ]
