# Generated by Django 4.2.18 on 2025-05-25 08:58

import dashboard.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_adminquery_predefinedquery_testcoverage_testresult_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', dashboard.models.CustomUserManager()),
            ],
        ),
    ]
