# Generated by Django 4.2.18 on 2025-05-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_predefinedquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedquery',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Analysis', 'Analysis'), ('Maintenance', 'Maintenance')], default='General', max_length=50),
        ),
    ]
