# Generated by Django 4.2.16 on 2025-03-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_predefinedquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AlterModelOptions(
            name='predefinedquery',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='savedquery',
            options={'ordering': ['-executed_at']},
        ),
        migrations.AlterField(
            model_name='predefinedquery',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
