# Generated by Django 5.2.6 on 2025-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_access_api_tools",
            field=models.BooleanField(
                default=True, help_text="Can access API Tools project"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_neo4j",
            field=models.BooleanField(
                default=True, help_text="Can access Neo4j Dashboard project"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_test_cases",
            field=models.BooleanField(
                default=True, help_text="Can access Test Cases project"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_wiremock",
            field=models.BooleanField(
                default=True, help_text="Can access Wiremock project"
            ),
        ),
    ]
