# Generated by Django 4.2.18 on 2025-05-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_predefinedquery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('coverage_percentage', models.FloatField()),
                ('lines_covered', models.IntegerField()),
                ('total_lines', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('SKIP', 'Skip')], max_length=20)),
                ('duration', models.FloatField()),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('test_file', models.CharField(max_length=255)),
                ('line_number', models.IntegerField()),
            ],
            options={
                'ordering': ['-last_run'],
            },
        ),
        migrations.CreateModel(
            name='ComponentDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('dependency_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source', 'target', 'dependency_type')},
            },
        ),
    ]
