# Generated by Django 5.2.6 on 2025-11-09 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="testcases.section",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "template",
                    models.CharField(default="Test Case (Steps)", max_length=100),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Functional", "Functional"),
                            ("Regression", "Regression"),
                            ("Smoke", "Smoke"),
                            ("Sanity", "Sanity"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=50,
                    ),
                ),
                ("estimate", models.CharField(blank=True, max_length=50)),
                (
                    "automation_type",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Automated", "Automated"),
                            ("Manual", "Manual"),
                        ],
                        default="None",
                        max_length=50,
                    ),
                ),
                ("reviewer", models.CharField(blank=True, max_length=200)),
                (
                    "labels",
                    models.CharField(
                        blank=True, help_text="Comma-separated labels", max_length=500
                    ),
                ),
                ("references", models.TextField(blank=True, max_length=200)),
                ("preconditions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_test_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="testcases.section",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("description", models.TextField()),
                ("expected_result", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="testcases.testcase",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
                "unique_together": {("test_case", "step_number")},
            },
        ),
    ]
